### ISSUE TITLE
Add explanation to Gradle files

### ISSUE THREAD

**Issue by bruce-forte** [ToxicBakery/Arbor#15]
Since this project is an example for configuring Maven deployment for Kotlin multiplatform projects it would be nice to have some documentation and also comments in the Gradle files which explain why certain things are there.

**Comment by ToxicBakery** [comment]
I'm happy to answer any questions but this is a bit broad. The respective libraries are better documentation than I can provide alone and while I won't suggest that this project is an easy to follow template, experienced gradle users should be generally able to understand what I've done throughout the project.

Feel free to ask specific questions and I'll try to answer those as best as I can.
